name = "loyorapay-prod"
compatibility_date = "2026-06-28"

routes = [
  { pattern = "loyorapay.com/*", zone_name = "loyorapay.com" },
  { pattern = "www.loyorapay.com/*", zone_name = "loyorapay.com" }
]

[assets]
directory = "."
