name = "loyorapay-prod"
compatibility_date = "2026-06-28"

[[routes]]
pattern = "loyorapay.com"
custom_domain = true

[[routes]]
pattern = "www.loyorapay.com"
custom_domain = true

[assets]
directory = "."
